language: node_js
node_js:
  - "stable"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm prune
  - npm install -g gulp
  - gulp bower
  - npm install -g karma
before_script:
  - cp -r Extra/src/ src/