language: node_js
node_js:
  - "5.6.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rm -rf node_modulee && rm -rf bower_components
  - npm install -g gulp
  - npm install -g karma
install:
  - ./install.sh
  # - npm install
  # - bower install && bower prune
before_script:
  - cp -r Extra/src/ src/
